[jobs.lab1]

image = { source = "dockerfile", path = "." }

run = [
    "java -classpath \".:lib/*:out\" com.cpunisher.hayasai.Main < \"$input\" > \"$ir\"",
]

[jobs.lab2]

image = { source = "dockerfile", path = "." }

run = [
    "java -classpath \".:lib/*:out\" com.cpunisher.hayasai.Main < \"$input\" > \"$ir\"",
]

[jobs.lab3]

image = { source = "dockerfile", path = "." }

run = [
    "java -classpath \".:lib/*:out\" com.cpunisher.hayasai.Main < \"$input\" > \"$ir\"",
]

[jobs.lab4]

image = { source = "dockerfile", path = "." }

run = [
    "java -ea -classpath \".:lib/*:out\" com.cpunisher.hayasai.Main < \"$input\" > \"$ir\"",
]